services:
  patientservice:
    image: patientservice
    container_name: patientservice
    build:
      context: .
      dockerfile: PatientService/Dockerfile
    depends_on:
      - sqlserver
    ports:
      - "7239:8083"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-CU8-ubuntu-18.04
    container_name: SQL-Server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Gk3vLNdhBQf9HMQc
    ports:
      - "1433:1433"
    volumes:
      - mysql-data:/var/lib/mysql  
  
  patientrapportdiabete:
    image: patientrapportdiabete
    container_name: patientrapportdiabete
    build:
      context: .
      dockerfile: PatientRapportDiabete/Dockerfile
    ports:
      - "7234:8082" 

  patientnote:
    image: patientnote
    container_name: patientnote
    build:
      context: .
      dockerfile: PatientNote/Dockerfile
    depends_on:
      - sqlserver
      - mongo
    ports:
      - "7078:8081" 

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017" 

  patientfront:
    image: patientfront
    container_name: patientfront
    build:
      context: .
      dockerfile: PatientFront/Dockerfile
    ports:
      - "7220:8080"
    environment:
        DatabaseServer: SQL-Server
        DatabasePort: 1433
        DatabaseUser: SA
        DatabasePassword: Gk3vLNdhBQf9HMQc
        DatabaseName: PatientMicroService
    depends_on:
        - sqlserver

  apigatewayocelot:
    image: apigatewayocelot
    container_name: apigatewayocelot
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=7202
      - PatientFrontUrl=http://localhost:7220
      - PatientServiceUrl=http://localhost:7239
      - PatientNoteUrl=http://localhost:7078
      - PatientRapportDiabeteUrl=http://localhost:7234
    build:
      context: .
      dockerfile: ApiGatewayOcelot/Dockerfile
    ports:
      - "7202:8084"

volumes:
  mysql-data: 
