version: '3'

services:
  patientservice:
    image: patientservice
    container_name: patientservice
    build:
      context: .
      dockerfile: PatientService/Dockerfile
    environment:
      - SQLSERVER_URL=Server=localhost;Integrated Security = True;Database=PatientMicroService;Trusted_Connection=True;TrustServerCertificate=True;
    ports:
      - "7239:8183"
 
  patientrapportdiabete:
    image: patientrapportdiabete
    container_name: patientrapportdiabete
    build:
      context: .
      dockerfile: PatientRapportDiabete/Dockerfile
    ports:
      - "7234:8182" 

  patientnote:
    image: patientnote
    container_name: patientnote
    build:
      context: .
      dockerfile: PatientNote/Dockerfile
    depends_on:
      - mongo
    environment:
      - SQLSERVER_URL=Server=localhost;Integrated Security = True;Database=PatientMicroService;Trusted_Connection=True;TrustServerCertificate=True; 
    ports:
      - "7078:8181" 

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017" 

  patientfront:
    image: patientfront
    container_name: patientfront
    build:
      context: .
      dockerfile: PatientFront/Dockerfile
    ports:
      - "7220:8180"

  apigatewayocelot:
    image: apigatewayocelot
    container_name: apigatewayocelot
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8184
      - PatientFrontUrl=https://localhost:7220
      - PatientServiceUrl=https://localhost:7239
      - PatientNoteUrl=https://localhost:7078
      - PatientRapportDiabeteUrl=https://localhost:7234
    build:
      context: .
      dockerfile: ApiGatewayOcelot/Dockerfile
    ports:
      - "7202:8184"
    depends_on:
      - patientservice

volumes:
  mongo-data: 
